# Memoracion, Jancen Johan
# 2ECEB

# Programming Assignment 2

Normalization Problem

In [1]:
#Syntax

In [2]:
import numpy as np

In [3]:
X = np.random.random((5,5))
X

array([[0.28440832, 0.97103313, 0.88152615, 0.00120423, 0.56070293],
       [0.22924413, 0.20624643, 0.14389875, 0.31832558, 0.17880632],
       [0.8076704 , 0.70442255, 0.12160946, 0.70545467, 0.30766744],
       [0.02527843, 0.81290749, 0.7935672 , 0.0273084 , 0.45913817],
       [0.01458069, 0.32569344, 0.01537028, 0.31008654, 0.90621214]])

In [4]:
Z = (X - X.mean())/X.std()
Z

array([[-0.37554149,  1.77171676,  1.49180465, -1.26119595,  0.48850518],
       [-0.54805457, -0.6199745 , -0.81495228, -0.26947321, -0.705787  ],
       [ 1.26083808,  0.93795461, -0.88465681,  0.94118235, -0.30280404],
       [-1.18590952,  1.27721586,  1.21673363, -1.17956127,  0.17088518],
       [-1.2193642 , -0.24643194, -1.21689494, -0.29523888,  1.56900429]])

In [5]:
np.save("X_normalized", Z)

Divisible by 3 Problem

In [6]:
#Syntax

In [7]:
import numpy as np

In [8]:
num = np.arange(1,101)
num

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [9]:
squared = num ** 2
squared

array([    1,     4,     9,    16,    25,    36,    49,    64,    81,
         100,   121,   144,   169,   196,   225,   256,   289,   324,
         361,   400,   441,   484,   529,   576,   625,   676,   729,
         784,   841,   900,   961,  1024,  1089,  1156,  1225,  1296,
        1369,  1444,  1521,  1600,  1681,  1764,  1849,  1936,  2025,
        2116,  2209,  2304,  2401,  2500,  2601,  2704,  2809,  2916,
        3025,  3136,  3249,  3364,  3481,  3600,  3721,  3844,  3969,
        4096,  4225,  4356,  4489,  4624,  4761,  4900,  5041,  5184,
        5329,  5476,  5625,  5776,  5929,  6084,  6241,  6400,  6561,
        6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,  8100,
        8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
       10000])

In [10]:
div_3 = squared[squared % 3 == 0]
div_3

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])

In [11]:
np.save("div_by_3", div_3)